import { jobSitePhotos } from "./images";

export interface RecentWorkPhoto {
  slug: string;
  webp: string;
  avif: string;
  thumb: string;
  /** JPG fallback when the picture sources are skipped. */
  jpg?: string;
  width: number;
  height: number;
  thumbWidth: number;
  thumbHeight: number;
  alt: string;
  caption: string;
  /** Set only when the manifest names a service page that already exists. */
  href?: string;
  linkLabel?: string;
}

/**
 * Job-site photos for the homepage recent-work strip and /work.
 * Older entries are Google Business Profile stills. Oct 5 blind and window
 * photos use the auditor alt text verbatim.
 */
export const recentWorkPhotos: RecentWorkPhoto[] = [
  {
    slug: jobSitePhotos.blindsInstallBrandedBack.slug,
    webp: jobSitePhotos.blindsInstallBrandedBack.webp,
    avif: jobSitePhotos.blindsInstallBrandedBack.avif,
    thumb: jobSitePhotos.blindsInstallBrandedBack.thumb,
    jpg: jobSitePhotos.blindsInstallBrandedBack.jpg,
    width: jobSitePhotos.blindsInstallBrandedBack.width,
    height: jobSitePhotos.blindsInstallBrandedBack.height,
    thumbWidth: jobSitePhotos.blindsInstallBrandedBack.thumbWidth,
    thumbHeight: jobSitePhotos.blindsInstallBrandedBack.thumbHeight,
    alt: jobSitePhotos.blindsInstallBrandedBack.alt,
    caption: "Window blind installation in a Tampa Bay home. The shirt shows the Handyman Pros Florida phone number.",
    href: "/services/handyman/general-repairs",
    linkLabel: "General repairs",
  },
  {
    slug: jobSitePhotos.blindsHardwareDrillProfile.slug,
    webp: jobSitePhotos.blindsHardwareDrillProfile.webp,
    avif: jobSitePhotos.blindsHardwareDrillProfile.avif,
    thumb: jobSitePhotos.blindsHardwareDrillProfile.thumb,
    jpg: jobSitePhotos.blindsHardwareDrillProfile.jpg,
    width: jobSitePhotos.blindsHardwareDrillProfile.width,
    height: jobSitePhotos.blindsHardwareDrillProfile.height,
    thumbWidth: jobSitePhotos.blindsHardwareDrillProfile.thumbWidth,
    thumbHeight: jobSitePhotos.blindsHardwareDrillProfile.thumbHeight,
    alt: jobSitePhotos.blindsHardwareDrillProfile.alt,
    caption: "Drilling blind hardware into a window frame with a cordless drill.",
    href: "/services/handyman/general-repairs",
    linkLabel: "General repairs",
  },
  {
    slug: jobSitePhotos.windowWorkBrandedShirt.slug,
    webp: jobSitePhotos.windowWorkBrandedShirt.webp,
    avif: jobSitePhotos.windowWorkBrandedShirt.avif,
    thumb: jobSitePhotos.windowWorkBrandedShirt.thumb,
    jpg: jobSitePhotos.windowWorkBrandedShirt.jpg,
    width: jobSitePhotos.windowWorkBrandedShirt.width,
    height: jobSitePhotos.windowWorkBrandedShirt.height,
    thumbWidth: jobSitePhotos.windowWorkBrandedShirt.thumbWidth,
    thumbHeight: jobSitePhotos.windowWorkBrandedShirt.thumbHeight,
    alt: jobSitePhotos.windowWorkBrandedShirt.alt,
    caption: "Branded uniform listing home repairs, painting, drywall, and fences.",
    href: "/services",
    linkLabel: "Home services",
  },
  {
    slug: jobSitePhotos.blindsInstallBrandedReach.slug,
    webp: jobSitePhotos.blindsInstallBrandedReach.webp,
    avif: jobSitePhotos.blindsInstallBrandedReach.avif,
    thumb: jobSitePhotos.blindsInstallBrandedReach.thumb,
    jpg: jobSitePhotos.blindsInstallBrandedReach.jpg,
    width: jobSitePhotos.blindsInstallBrandedReach.width,
    height: jobSitePhotos.blindsInstallBrandedReach.height,
    thumbWidth: jobSitePhotos.blindsInstallBrandedReach.thumbWidth,
    thumbHeight: jobSitePhotos.blindsInstallBrandedReach.thumbHeight,
    alt: jobSitePhotos.blindsInstallBrandedReach.alt,
    caption: "Installing white mini blinds at a residential window.",
    href: "/services/handyman/general-repairs",
    linkLabel: "General repairs",
  },
  {
    slug: "backyard-gravel-landscape-prep",
    webp: "/images/work/handyman-pros-florida-tampa-bay-backyard-gravel-landscape-prep.webp",
    avif: "/images/work/handyman-pros-florida-tampa-bay-backyard-gravel-landscape-prep.avif",
    thumb: "/images/work/handyman-pros-florida-tampa-bay-backyard-gravel-landscape-prep-thumb.webp",
    width: 1400,
    height: 1866,
    thumbWidth: 800,
    thumbHeight: 1066,
    alt: "Landscape fabric and gray gravel being prepared along a fenced backyard side passage",
    caption:
      "Backyard side passage prepared with landscape fabric and gravel beside a fence and air-conditioning unit.",
  },
  {
    slug: "built-in-wall-niches",
    webp: "/images/work/handyman-pros-florida-tampa-bay-built-in-wall-niches.webp",
    avif: "/images/work/handyman-pros-florida-tampa-bay-built-in-wall-niches.avif",
    thumb: "/images/work/handyman-pros-florida-tampa-bay-built-in-wall-niches-thumb.webp",
    width: 1600,
    height: 1200,
    thumbWidth: 800,
    thumbHeight: 600,
    alt: "Finished built-in wall niches above drawer cabinets with recessed ceiling lights",
    caption: "Finished built-in wall niches above drawer cabinets with recessed ceiling lights.",
  },
  {
    slug: "large-format-tile-floor-installation",
    webp: "/images/work/handyman-pros-florida-tampa-bay-large-format-tile-floor-installation.webp",
    avif: "/images/work/handyman-pros-florida-tampa-bay-large-format-tile-floor-installation.avif",
    thumb: "/images/work/handyman-pros-florida-tampa-bay-large-format-tile-floor-installation-thumb.webp",
    width: 1600,
    height: 1200,
    thumbWidth: 800,
    thumbHeight: 600,
    alt: "Large light-colored floor tiles installed across a kitchen and living area under renovation",
    caption: "Large-format light tile flooring installed across a kitchen and living area.",
    href: "/services/tile-installation",
    linkLabel: "Tile installation",
  },
  {
    slug: "drywall-rounded-window-opening",
    webp: "/images/work/handyman-pros-florida-tampa-bay-drywall-rounded-window-opening.webp",
    avif: "/images/work/handyman-pros-florida-tampa-bay-drywall-rounded-window-opening.avif",
    thumb: "/images/work/handyman-pros-florida-tampa-bay-drywall-rounded-window-opening-thumb.webp",
    width: 1600,
    height: 1200,
    thumbWidth: 800,
    thumbHeight: 600,
    alt: "Smooth drywall wall with a rounded window opening and a step ladder",
    caption: "Drywall-finished wall with a rounded window opening, ready for final trim.",
    href: "/services/drywall-repair",
    linkLabel: "Drywall repair",
  },
  {
    slug: "built-in-console-drywall",
    webp: "/images/work/handyman-pros-florida-tampa-bay-built-in-console-drywall.webp",
    avif: "/images/work/handyman-pros-florida-tampa-bay-built-in-console-drywall.avif",
    thumb: "/images/work/handyman-pros-florida-tampa-bay-built-in-console-drywall-thumb.webp",
    width: 1400,
    height: 1050,
    thumbWidth: 800,
    thumbHeight: 600,
    alt: "Built-in drawer cabinets and a console under construction against a patched drywall wall",
    caption: "Built-in drawer cabinets and console taking shape against a patched drywall wall.",
  },
  {
    slug: "drywall-wall-repair-under-window",
    webp: "/images/work/handyman-pros-florida-tampa-bay-drywall-wall-repair-under-window.webp",
    avif: "/images/work/handyman-pros-florida-tampa-bay-drywall-wall-repair-under-window.avif",
    thumb: "/images/work/handyman-pros-florida-tampa-bay-drywall-wall-repair-under-window-thumb.webp",
    width: 1400,
    height: 1050,
    thumbWidth: 800,
    thumbHeight: 600,
    alt: "Handyman Pros Florida technician patching and finishing drywall under a window",
    caption: "Drywall wall repair under a window",
    href: "/services/drywall-repair",
    linkLabel: "Drywall repair",
  },
  {
    slug: "drywall-room-window-prep",
    webp: "/images/work/handyman-pros-florida-tampa-bay-drywall-room-window-prep.webp",
    avif: "/images/work/handyman-pros-florida-tampa-bay-drywall-room-window-prep.avif",
    thumb: "/images/work/handyman-pros-florida-tampa-bay-drywall-room-window-prep-thumb.webp",
    width: 1400,
    height: 1050,
    thumbWidth: 800,
    thumbHeight: 600,
    alt: "Unfinished room with drywall mud work around windows and a door, materials staged",
    caption: "Drywall prep around windows and door",
    href: "/services/drywall-repair",
    linkLabel: "Drywall repair",
  },
  {
    slug: "drywall-room-chandelier-prep",
    webp: "/images/work/handyman-pros-florida-tampa-bay-drywall-room-chandelier-prep.webp",
    avif: "/images/work/handyman-pros-florida-tampa-bay-drywall-room-chandelier-prep.avif",
    thumb: "/images/work/handyman-pros-florida-tampa-bay-drywall-room-chandelier-prep-thumb.webp",
    width: 1400,
    height: 1050,
    thumbWidth: 800,
    thumbHeight: 600,
    alt: "Room under drywall repair with chandelier, masked doorway, and tools on the floor",
    caption: "Drywall repair room with chandelier",
    href: "/services/drywall-repair",
    linkLabel: "Drywall repair",
  },
  {
    slug: "drywall-finishing-worker",
    webp: "/images/work/handyman-pros-florida-tampa-bay-drywall-finishing-worker.webp",
    avif: "/images/work/handyman-pros-florida-tampa-bay-drywall-finishing-worker.avif",
    thumb: "/images/work/handyman-pros-florida-tampa-bay-drywall-finishing-worker-thumb.webp",
    width: 1400,
    height: 1050,
    thumbWidth: 800,
    thumbHeight: 600,
    alt: "Worker finishing patched drywall in a room protected with plastic sheeting",
    caption: "Drywall finishing with plastic protection",
    href: "/services/drywall-repair",
    linkLabel: "Drywall repair",
  },
  {
    slug: "protected-room-drywall-work",
    webp: "/images/work/handyman-pros-florida-tampa-bay-protected-room-drywall-work.webp",
    avif: "/images/work/handyman-pros-florida-tampa-bay-protected-room-drywall-work.avif",
    thumb: "/images/work/handyman-pros-florida-tampa-bay-protected-room-drywall-work-thumb.webp",
    width: 1400,
    height: 1050,
    thumbWidth: 800,
    thumbHeight: 600,
    alt: "Room masked for drywall work with taped windows and protective coverings over furnishings",
    caption: "Masked room ready for drywall work",
    href: "/services/drywall-repair",
    linkLabel: "Drywall repair",
  },
];
