export const siteConfig = {
  name: "Handyman Pros Florida",
  shortName: "Handyman Pros FL",
  domain: "handymanprosflorida.com",
  url: "https://handymanprosflorida.com",
  description:
    "Licensed & insured handyman based at 12021 Tuscany Bay Dr, Tampa FL 33626. Open 24/7 serving Westchase, Carrollwood, Citrus Park, Hillsborough County & Tampa Bay. Furniture assembly, drywall, painting, fences & emergency repairs.",
  tagline: "Your Tampa Handyman — Done Right, Done Fast",
  phone: "(656) 205-3185",
  phoneTel: "+16562053185",
  email: "support@handymanprosflorida.com",
  address: {
    street: "12021 Tuscany Bay Dr",
    street2: "Apt 203",
    city: "Tampa",
    state: "FL",
    zip: "33626",
    country: "US",
    neighborhood: "Westchase",
  },
  geo: {
    latitude: 28.0521,
    longitude: -82.6136,
  },
  hoursLabel: "Open 24/7",
  hours: [
    { day: "Monday", opens: "00:00", closes: "23:59" },
    { day: "Tuesday", opens: "00:00", closes: "23:59" },
    { day: "Wednesday", opens: "00:00", closes: "23:59" },
    { day: "Thursday", opens: "00:00", closes: "23:59" },
    { day: "Friday", opens: "00:00", closes: "23:59" },
    { day: "Saturday", opens: "00:00", closes: "23:59" },
    { day: "Sunday", opens: "00:00", closes: "23:59" },
  ],
  social: {
    facebook: "https://www.facebook.com/handymanprosflorida",
    instagram: "https://www.instagram.com/handymanprosflorida",
    google: "https://g.page/handymanprosflorida",
  },
  counties: [
    "Hillsborough County",
    "Pinellas County",
    "Pasco County",
    "Polk County",
    "Hernando County",
    "Manatee County",
  ],
  serviceAreas: [
    "Tampa",
    "Westchase",
    "Tuscany Bay",
    "Carrollwood",
    "Citrus Park",
    "Town 'n' Country",
    "Keystone",
    "Cheval",
    "Oldsmar",
    "Brandon",
    "Riverview",
    "Temple Terrace",
    "Plant City",
    "South Tampa",
    "Hyde Park",
    "New Tampa",
    "St. Petersburg",
    "Clearwater",
    "Largo",
    "Dunedin",
    "Safety Harbor",
    "Wesley Chapel",
    "Land O' Lakes",
    "New Port Richey",
    "Lakeland",
    "Bradenton",
    "Apollo Beach",
    "Valrico",
    "Fish Hawk",
    "Lutz",
  ],
  keywords: [
    "handyman Tampa FL",
    "handyman Westchase",
    "handyman 33626",
    "handyman Hillsborough County",
    "handyman Carrollwood",
    "handyman Citrus Park",
    "handyman Town n Country",
    "handyman near me Tampa",
    "home repair Tampa FL",
    "painting contractor Tampa",
    "fence repair Tampa Bay",
    "furniture assembly Tampa",
    "drywall repair Tampa",
    "emergency handyman Tampa 24/7",
    "licensed handyman Tampa Bay",
    "handyman Pinellas County",
    "handyman Brandon FL",
    "handyman St Petersburg",
    "affordable handyman Tampa",
    "local handyman Tampa Bay",
  ],
  indexNowKey: "8f3a7c2e1b9d4f6a8c5e2b7d1a9f4c6e",
  themeColor: "#f2760f",
} as const;

export type ServiceCategory = "handyman" | "painting" | "fence";

export interface Service {
  slug: string;
  name: string;
  category: ServiceCategory;
  shortDescription: string;
  description: string;
  keywords: string[];
  faqs: { question: string; answer: string }[];
}
